# Numpy Tutorial
Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

## What is an array?
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While Python lists can contain values corresponding to different data types, arrays in Python can only contain values corresponding to same data type.

## Why we use array?
- Array operations are very very fast.
- Most of the time we use two dimentional array in Exploratory Data Analysis.
- We use Numpy arrays to quickly train the machine learning model.

## Topics we cover in this Tutorial
1. How to create array?
2. How to manipulate or change the shape of array?
3. How to retrive the data from array or indexing of array?
4. What type of conditions in array?
5. What type of arithmetic operations in array?
6. Some important methods of Numpy.
7. Random methods in Numpy.

In [32]:
# First of all lets import numpy module and give it a short discriptive name 'np'.
import numpy as np

## 1. Array Creation
- <b>arange(start, Stop, Step)</b>
    - arange() is a builtin numpy method use to generate array just like range() function. Where range() function returns a list object and np.arange() method returns an array object.
   
    - First three commonly use parameters of arange() method are np.arange(Start,Stop,Step).
   
    - If you only put one parameter that means np.arange(Stop).

- <b>array(data)</b>
    - array() is a builtin numpy method to convert different data types like lits, tupli, etc into array.

In [33]:
# Generating array by passing starting and ending (but not included) points in numpy arange() method.
array_1 = np.arange(100)    
array_2 = np.arange(1,21)
array_3 = np.arange(10,100,10)

print("\narray_1\n",array_1)
print("\narray_2\n",array_2)
print("\narray_3\n",array_3)
array_1


array_1
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

array_2
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

array_3
 [10 20 30 40 50 60 70 80 90]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
# Generating one dimentional array by passing a list in numpy array() method.
my_list = [1,2,3,4,5]
array = np.array(my_list)
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [35]:
# Generating two dimentional array by passing three lists in numpy array method. 
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
list_3 = [11,12,13,14,15]

array = np.array([list_1,list_2,list_3])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## 2. Array Manipulation or Shaping.

- There are arrays of multiple shapes.

- We can check shape of an array by calling <b>shape</b> property.

- We can change the shape of an array by calling <b>reshape()</b> method.

- </b>reshape()</b> gives a new shape to an array without changing its data.

- It is just a handy way to make a difference between array of different dimensions by looking at the brackets of an array for example. 
    - One dimensional array have single starting and closing bracket '[1,2,3,...,n\]'
    - Two dimensional array have double starting and closing bracket '[[1,2,3,...,n\]\]'
    - <b>Note</b> this is just a tric and not always work in every condition.

In [36]:
# We can check shape of an array by calling shape property.
array = np.arange(15)
print(f"One dimentional array is shown as '{array.shape}'.")
array

One dimentional array is shown as '(15,)'.


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
# We can also change the shape of array by calling reshape method. 
array.reshape(5,3)  # 5 x 3 = 15

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [38]:
# Changing shape from 5x3 to 1x15 but the array will remains two dimentional.
array = array.reshape(1,15)
print(array)

print("\nThis looks like one dimensional array but it is two dimensional array, looks at the double brakets.\n")
print(f"The shape of this array is 1 raw and 15 columns {array.shape}.")

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]

This looks like one dimensional array but it is two dimensional array, looks at the double brakets.

The shape of this array is 1 raw and 15 columns (1, 15).


In [39]:
# Changing shape from 5x3 to 1x15 but this time array converts to one dimentional.
array.reshape(15,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
# Another way to change the shape of an array.
array.shape = (3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 3. Array Indexing
- We use indexing to <b>retrive</b> the data.
- We use <b>sub</b> or <b>index</b> operator for data retrival.
- The sub operator is denoted by square brackets <b>"[]"</b>.


In [41]:
array = np.arange(15).reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
# 1:3 selecting raw from index "1" to index "3" but not including 3.
# 2:4 selecting column from index "2" to index "4" but not including 4.
array[1:3,2:4] 

array([[ 7,  8],
       [12, 13]])

In [43]:
array[1:2,1:-1]

array([[6, 7, 8]])

## 4. Conditions in Array.
- Some Important Conditions used in Exploratory Data Analysis.

- When condition or arithimetic operation apply on an array without brackets (ie: array > 2) it will give you all True and False values or the values.

- When condition apply on an array with brackets (ie: array\[array > 2\]) it will give you the True values, Make sure you provide the condition not arithomatic operation.

In [44]:
array = np.arange(15).reshape(3,5)
array[array > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
val = 2
print(array, 'array \n')
print(array + val, 'array + 2 \n')
print(array - val, 'array - 2 \n')
print(array * val, 'array * 2 \n')
print(array / val, 'array / 2 \n')
print(array % val, 'array % 2 \n')
print(array > val, 'array > 2 \n')
print(array < val, 'array < 2 \n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] array 

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]] array + 2 

[[-2 -1  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]] array - 2 

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]] array * 2 

[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]] array / 2 

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]] array % 2 

[[False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] array > 2 

[[ True  True False False False]
 [False False False False False]
 [False False False False False]] array < 2 



In [46]:
print(f"{array[array%2 == 0]}\t= arr%2 == 0 \n")
print(f"{array[array > 2]}\t= arr > 2 \n")
print(f"{array[array != 5]}\t= arr != 5 \n")
print(f"{array[array == 5]}\t= arr == 5 \n")

[ 0  2  4  6  8 10 12 14]	= arr%2 == 0 

[ 3  4  5  6  7  8  9 10 11 12 13 14]	= arr > 2 

[ 0  1  2  3  4  6  7  8  9 10 11 12 13 14]	= arr != 5 

[5]	= arr == 5 



## 5. Arithmatic Operation
- Applying arithmatic operation between two arrays.

In [47]:
array_1 = np.arange(2,21,2).reshape(2,5)
print(array_1,'\n')
array_2 = np.arange(3,31,3).reshape(2,5)
print(array_2)

[[ 2  4  6  8 10]
 [12 14 16 18 20]] 

[[ 3  6  9 12 15]
 [18 21 24 27 30]]


In [48]:
array_1 + array_2

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [49]:
array_2 - array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
array_1 * array_2

array([[  6,  24,  54,  96, 150],
       [216, 294, 384, 486, 600]])

In [51]:
array_2 / array_1

array([[1.5, 1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5, 1.5]])

In [52]:
array_1 % array_2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]], dtype=int32)

## 6. Builtin Methods
Following are some importanat builtin methods of numpy.

<b>6.1) ones() and zeros()</b>
      
- ones() creates array where all the elements are one.
- zero() creates array where all the elements are zero.

<b>6.2) linspace()</b> 

-  It generate special kind series in which the differnce between all elements is equal.

<b>6.3) copy()</b> 
    
-  It is used to copy an arry while assigning one arry form one variable to another, this provide solution of ie:.reference type vs value type, by creating a new memory for copied variable.



### 6.1 ones(shape, dtype=float) Method

In [53]:
print(np.ones(4))           # one dimentional array with all floating point ones.
print(np.ones(4,dtype=int)) # one dimentional array with all integer ones.
print(np.ones((3,5)))       # two dimentional array with 3 raws and 5 columns.

[1. 1. 1. 1.]
[1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 6.1 zeros() Method

In [54]:
print(np.zeros(4))           # one dimentional array with all floating point zeros.
print(np.zeros(4,dtype=int)) # one dimentional array with all integer zeros.
print(np.zeros((3,5)))       # two dimentional array with 3 raws and 5 columns.

[0. 0. 0. 0.]
[0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 6.2) linspace() Method
- The numpy linspace function creates sequences of evenly spaced values within a defined interval.

- Elements in an array generated by linspace() are floating points.

In [55]:
array = np.linspace(10,100,10) # Start from 10 to 100 with 10 elemets
print(array)
print(type(array[0]))

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
<class 'numpy.float64'>


In [56]:
array = np.linspace(0,100) # The 3rd parameter of linspace() method is by default 50
array

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

### 6.3) copy() Method and Brodcasting

- Brodcasting means to replace array elements with another serires.

- In array we have a concept of refrence type by which two or more variable have same memory locations which make conflict. When we apply brodcasting or any changing to one variable the others will automatically change due to the same memory location.

- So we apply copy() method when making copy of one array from one variable to another for resolving the conflict.

- Their is also a concept of value type in Python.

- Memory location of a variable can be chacked by Python's builtin function "id()".

In [57]:
# Defining the problem.
# Creating two arrays.
array_1 = np.arange(10)
array_2 = array_1

# Both array_1 and array_2 have same memory location.
print(id(array_1))
print(id(array_2))

# Applying broadcasting
array_2[5:] = 55                # making change in array_2
print("array_1 =",array_1)      # array_2 change
print("array_2 =",array_2)      # array_1 also change at this point problem occurs.

119379232
119379232
array_1 = [ 0  1  2  3  4 55 55 55 55 55]
array_2 = [ 0  1  2  3  4 55 55 55 55 55]


In [58]:
# Solving the problem with copy() method.
array_1 = np.arange(10)

# But this time we assign array_1 with copy() method which creates a sperate memery location for array_2 variable.
array_2 = array_1.copy() 

# Now both array_1 and array_2 have different memory locations.
print(id(array_1))
print(id(array_2))

# Applying broadcasting.
array_2[5:] = 55                # making change in array_2
print("array_1 =",array_1)      # array_2 change
print("array_2 =",array_2)      # array_1 does not change :)

100343584
100340944
array_1 = [0 1 2 3 4 5 6 7 8 9]
array_2 = [ 0  1  2  3  4 55 55 55 55 55]


## 7 Numpy Random Methods.

<b> 7.1) np.random.rand(shape)</b>
- It creates an array if given shape with random values.

<b> 7.2) np.random.randn(shape)</b>
- It creates an array if given shape with random values.

<b> 7.3) np.random.randint(shape)</b>
- It creates an array if given shape with random values.



### 7.1) np.random.rand(shape)
- Random values in a given shape. 
- Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0,  1]``.

In [59]:
np.random.rand(2,5) # Every time we got new numbers because this is random.

array([[0.13493229, 0.17507564, 0.61533962, 0.14265619, 0.3136348 ],
       [0.6058091 , 0.72706227, 0.44114396, 0.25267414, 0.22135181]])

### 7.2 np.random.randn(shape)
- Return a sample (or samples) from the "standard normal" distribution.

In [60]:
np.random.randn(2,5)

array([[-0.94534149, -0.67875853, -0.4406494 ,  0.50054272, -0.88193387],
       [ 0.94686585,  0.74231214,  0.1209196 ,  0.08239601,  0.41652007]])

### 7.3 np.random.randint()

- it generate array between lower value and higher value and fill randomly with integers

In [61]:
np.random.randint(0,50,7)

array([37, 44, 25, 47, 20, 25, 15])