# Pandas Tutorial
Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

## Agenda

- What is Data Frames?
- What is Data Series?
- Different operation in Pandas

In [1]:
import numpy as np
import pandas as pd

In [7]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Generating Data Frame with numpy and pandas

In [2]:
df = pd.DataFrame(np.arange(1,21).reshape(4,5),index=['Raw_1', 'Raw_2', 'Raw_3', 'Raw_4'],columns=['Column_1', 'Column_2', 'Column_3', 'Column_4', 'Column_5'])

In [13]:
df.head()

Coloumn_1  Coloumn_2  Coloumn_3  Coloumn_4  Coloumn_5
Raw_1          1          2          3          4          5
Raw_2          6          7          8          9         10
Raw_3         11         12         13         14         15
Raw_4         16         17         18         19         20

In [36]:
df_0 = pd.DataFrame(np.arange(1,6).reshape(1,5),index=['Raw_1'],columns=['Coloumn_1', 'Coloumn_2', 'Coloumn_3', 'Coloumn_4', 'Coloumn_5'])

In [38]:
type(df_0.head())

pandas.core.frame.DataFrame

## Putting this Data Frame into a CSV file or an Excel file with .to_csv() method.

In [15]:
df.to_csv('Test.csv')

## Accessing index values
### First Approach
- .loc()
- This returns a series of a raw.

### Second Approach
- .iloc()
- this returns a dataframe which is the set of raws and coulmns

In [43]:
df

Coloumn_1  Coloumn_2  Coloumn_3  Coloumn_4  Coloumn_5
Raw_1          1          2          3          4          5
Raw_2          6          7          8          9         10
Raw_3         11         12         13         14         15
Raw_4         16         17         18         19         20

In [42]:
# loc method
print(df.loc['Raw_4'])
type(df.loc['Raw_2'])

Coloumn_1    16
Coloumn_2    17
Coloumn_3    18
Coloumn_4    19
Coloumn_5    20
Name: Raw_4, dtype: int32


pandas.core.series.Series

In [44]:
# iloc method
df.iloc[1: , 1:4]

Coloumn_2  Coloumn_3  Coloumn_4
Raw_2          7          8          9
Raw_3         12         13         14
Raw_4         17         18         19